config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :inventaries
  resources :items
  resources :status_change_resistances
  resources :quasi_stats
  resources :sub_stats
  resources :stats
  resources :jobs
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_stat.rb
class SubStat < ApplicationRecord
	belongs_to :stat
end

app/controllers/sub_stats_controller.rb
class SubStatsController < ApplicationController
  before_action :set_sub_stat, only: [:show, :edit, :update, :destroy]

  # GET /sub_stats
  # GET /sub_stats.json
  def index
    @sub_stats = SubStat.all
  end

  # GET /sub_stats/1
  # GET /sub_stats/1.json
  def show
  end

  # GET /sub_stats/new
  def new
    @sub_stat = SubStat.new
  end

  # GET /sub_stats/1/edit
  def edit
  end

  # POST /sub_stats
  # POST /sub_stats.json
  def create
    @sub_stat = SubStat.new(sub_stat_params)

    respond_to do |format|
      if @sub_stat.save
        format.html { redirect_to @sub_stat, notice: 'Sub stat was successfully created.' }
        format.json { render :show, status: :created, location: @sub_stat }
      else
        format.html { render :new }
        format.json { render json: @sub_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_stats/1
  # PATCH/PUT /sub_stats/1.json
  def update
    respond_to do |format|
      if @sub_stat.update(sub_stat_params)
        format.html { redirect_to @sub_stat, notice: 'Sub stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_stat }
      else
        format.html { render :edit }
        format.json { render json: @sub_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_stats/1
  # DELETE /sub_stats/1.json
  def destroy
    @sub_stat.destroy
    respond_to do |format|
      format.html { redirect_to sub_stats_url, notice: 'Sub stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_stat
      @sub_stat = SubStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_stat_params
      params.require(:sub_stat).permit(:atk, :matk, :def, :mdef, :hit, :crit, :flee, :aspd, :hp, :sp)
    end
end

app/helpers/sub_stats_helper.rb
module SubStatsHelper
end

app/views/sub_stats/_form.html.erb
<%= form_with(model: sub_stat, local: true) do |form| %>
  <% if sub_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_stat.errors.count, "error") %> prohibited this sub_stat from being saved:</h2>

      <ul>
      <% sub_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :atk %>
    <%= form.number_field :atk, id: :sub_stat_atk %>
  </div>

  <div class="field">
    <%= form.label :matk %>
    <%= form.number_field :matk, id: :sub_stat_matk %>
  </div>

  <div class="field">
    <%= form.label :def %>
    <%= form.number_field :def, id: :sub_stat_def %>
  </div>

  <div class="field">
    <%= form.label :mdef %>
    <%= form.number_field :mdef, id: :sub_stat_mdef %>
  </div>

  <div class="field">
    <%= form.label :hit %>
    <%= form.number_field :hit, id: :sub_stat_hit %>
  </div>

  <div class="field">
    <%= form.label :crit %>
    <%= form.number_field :crit, id: :sub_stat_crit %>
  </div>

  <div class="field">
    <%= form.label :flee %>
    <%= form.number_field :flee, id: :sub_stat_flee %>
  </div>

  <div class="field">
    <%= form.label :aspd %>
    <%= form.number_field :aspd, id: :sub_stat_aspd %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp, id: :sub_stat_hp %>
  </div>

  <div class="field">
    <%= form.label :sp %>
    <%= form.number_field :sp, id: :sub_stat_sp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_stats/edit.html.erb
<h1>Editing Sub Stat</h1>

<%= render 'form', sub_stat: @sub_stat %>

<%= link_to 'Show', @sub_stat %> |
<%= link_to 'Back', sub_stats_path %>

app/views/sub_stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Stats</h1>

<table>
  <thead>
    <tr>
      <th>Atk</th>
      <th>Matk</th>
      <th>Def</th>
      <th>Mdef</th>
      <th>Hit</th>
      <th>Crit</th>
      <th>Flee</th>
      <th>Aspd</th>
      <th>Hp</th>
      <th>Sp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_stats.each do |sub_stat| %>
      <tr>
        <td><%= sub_stat.atk %></td>
        <td><%= sub_stat.matk %></td>
        <td><%= sub_stat.def %></td>
        <td><%= sub_stat.mdef %></td>
        <td><%= sub_stat.hit %></td>
        <td><%= sub_stat.crit %></td>
        <td><%= sub_stat.flee %></td>
        <td><%= sub_stat.aspd %></td>
        <td><%= sub_stat.hp %></td>
        <td><%= sub_stat.sp %></td>
        <td><%= link_to 'Show', sub_stat %></td>
        <td><%= link_to 'Edit', edit_sub_stat_path(sub_stat) %></td>
        <td><%= link_to 'Destroy', sub_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Stat', new_sub_stat_path %>

app/views/sub_stats/new.html.erb
<h1>New Sub Stat</h1>

<%= render 'form', sub_stat: @sub_stat %>

<%= link_to 'Back', sub_stats_path %>

app/views/sub_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Atk:</strong>
  <%= @sub_stat.atk %>
</p>

<p>
  <strong>Matk:</strong>
  <%= @sub_stat.matk %>
</p>

<p>
  <strong>Def:</strong>
  <%= @sub_stat.def %>
</p>

<p>
  <strong>Mdef:</strong>
  <%= @sub_stat.mdef %>
</p>

<p>
  <strong>Hit:</strong>
  <%= @sub_stat.hit %>
</p>

<p>
  <strong>Crit:</strong>
  <%= @sub_stat.crit %>
</p>

<p>
  <strong>Flee:</strong>
  <%= @sub_stat.flee %>
</p>

<p>
  <strong>Aspd:</strong>
  <%= @sub_stat.aspd %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @sub_stat.hp %>
</p>

<p>
  <strong>Sp:</strong>
  <%= @sub_stat.sp %>
</p>

<%= link_to 'Edit', edit_sub_stat_path(@sub_stat) %> |
<%= link_to 'Back', sub_stats_path %>