config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :inventaries
  resources :items
  resources :status_change_resistances
  resources :quasi_stats
  resources :sub_stats
  resources :stats
  resources :jobs
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
	after_initialize :default_values
	before_save :set_stats
	belongs_to :job
	has_one :stat, dependent: :destroy
	accepts_nested_attributes_for :stat, allow_destroy: true

private
  def default_values
    self.job = Job.find_by(level: 0)
    self.level = 1
    self.experience = 0
  end

  def set_stats
    self.stat = Stat.new(str:1, agi: 1, vit: 1, int: 1, dex: 1, luk: 1)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show

  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :gender, :level, :experience)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :character_name %>
  </div>

  <div class="field">
    <%= form.select(:gender, [['Male', 'Male'], ['Female', 'Female']]) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Job</th>
      <th>Level</th>
      <th>Experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.gender %></td>
        <td><%= character.job.name %></td>
        <td><%= character.level %></td>
        <td><%= character.experience %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>
<div>
	<h1>
	  <strong>Name:</strong>
	  <%= @character.name %>
	</h1>

	<p>
	  <strong>Gender:</strong>
	  <%= @character.gender %>
	</p>

	<p>
	  <strong>Job:</strong>
	  <%= @character.job.name %>
	</p>

	<p>
	  <strong>LVL (Level):</strong>
	  <%= @character.level %>
	</p>

	<p>
	  <strong>EXP (Experience):</strong>
	  <%= @character.experience %>
	</p>
</div>
<div class="col-md-3">
	<h2>
		<strong>Stats:</strong>
	</h2>

	<p>
	  <strong>STR (Stregth):</strong>
	  <%= @character.stat.str %>
	</p>

	<p>
	  <strong>AGI (Agility):</strong>
	  <%= @character.stat.agi %>
	</p>

	<p>
	  <strong>VIT (Vitality):</strong>
	  <%= @character.stat.vit %>
	</p>

	<p>
	  <strong>INT (Intelligence):</strong>
	  <%= @character.stat.int %>
	</p>

	<p>
	  <strong>DEX (Dexterity):</strong>
	  <%= @character.stat.dex %>
	</p>

	<p>
	  <strong>LUK (Luck):</strong>
	  <%= @character.stat.luk %>
	</p>
</div>
<div>
	<h2>
		<strong>Substats:</strong>
	</h2>

	<p>
	  <strong>ATK (Attack):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>MATK (Magic Attack):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>DEF (Defense):</strong>
	  
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>MDEF (Magic Defense):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>HIT (Hit rate):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>CRIT (Critical Hit Rate):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>FLEE (Flee rate):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>ASPD (Attack Speed):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>HP (Health Points):</strong>
	  <%= @character.stat.luk %>
	</p>

	<p>
	  <strong>SP (Spell Power):</strong>
	  <%= @character.stat.luk %>
	</p>
</div>
<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>