config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :inventaries
  resources :items
  resources :status_change_resistances
  resources :quasi_stats
  resources :sub_stats
  resources :stats
  resources :jobs
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quasi_stat.rb
class QuasiStat < ApplicationRecord
end

app/controllers/quasi_stats_controller.rb
class QuasiStatsController < ApplicationController
  before_action :set_quasi_stat, only: [:show, :edit, :update, :destroy]

  # GET /quasi_stats
  # GET /quasi_stats.json
  def index
    @quasi_stats = QuasiStat.all
  end

  # GET /quasi_stats/1
  # GET /quasi_stats/1.json
  def show
  end

  # GET /quasi_stats/new
  def new
    @quasi_stat = QuasiStat.new
  end

  # GET /quasi_stats/1/edit
  def edit
  end

  # POST /quasi_stats
  # POST /quasi_stats.json
  def create
    @quasi_stat = QuasiStat.new(quasi_stat_params)

    respond_to do |format|
      if @quasi_stat.save
        format.html { redirect_to @quasi_stat, notice: 'Quasi stat was successfully created.' }
        format.json { render :show, status: :created, location: @quasi_stat }
      else
        format.html { render :new }
        format.json { render json: @quasi_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quasi_stats/1
  # PATCH/PUT /quasi_stats/1.json
  def update
    respond_to do |format|
      if @quasi_stat.update(quasi_stat_params)
        format.html { redirect_to @quasi_stat, notice: 'Quasi stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @quasi_stat }
      else
        format.html { render :edit }
        format.json { render json: @quasi_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quasi_stats/1
  # DELETE /quasi_stats/1.json
  def destroy
    @quasi_stat.destroy
    respond_to do |format|
      format.html { redirect_to quasi_stats_url, notice: 'Quasi stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quasi_stat
      @quasi_stat = QuasiStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quasi_stat_params
      params.require(:quasi_stat).permit(:atk_range, :cast_time, :weight_limit, :energy)
    end
end

app/helpers/quasi_stats_helper.rb
module QuasiStatsHelper
end

app/views/quasi_stats/_form.html.erb
<%= form_with(model: quasi_stat, local: true) do |form| %>
  <% if quasi_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quasi_stat.errors.count, "error") %> prohibited this quasi_stat from being saved:</h2>

      <ul>
      <% quasi_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :atk_range %>
    <%= form.number_field :atk_range, id: :quasi_stat_atk_range %>
  </div>

  <div class="field">
    <%= form.label :cast_time %>
    <%= form.number_field :cast_time, id: :quasi_stat_cast_time %>
  </div>

  <div class="field">
    <%= form.label :weight_limit %>
    <%= form.number_field :weight_limit, id: :quasi_stat_weight_limit %>
  </div>

  <div class="field">
    <%= form.label :energy %>
    <%= form.number_field :energy, id: :quasi_stat_energy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quasi_stats/edit.html.erb
<h1>Editing Quasi Stat</h1>

<%= render 'form', quasi_stat: @quasi_stat %>

<%= link_to 'Show', @quasi_stat %> |
<%= link_to 'Back', quasi_stats_path %>

app/views/quasi_stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quasi Stats</h1>

<table>
  <thead>
    <tr>
      <th>Atk range</th>
      <th>Cast time</th>
      <th>Weight limit</th>
      <th>Energy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quasi_stats.each do |quasi_stat| %>
      <tr>
        <td><%= quasi_stat.atk_range %></td>
        <td><%= quasi_stat.cast_time %></td>
        <td><%= quasi_stat.weight_limit %></td>
        <td><%= quasi_stat.energy %></td>
        <td><%= link_to 'Show', quasi_stat %></td>
        <td><%= link_to 'Edit', edit_quasi_stat_path(quasi_stat) %></td>
        <td><%= link_to 'Destroy', quasi_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quasi Stat', new_quasi_stat_path %>

app/views/quasi_stats/new.html.erb
<h1>New Quasi Stat</h1>

<%= render 'form', quasi_stat: @quasi_stat %>

<%= link_to 'Back', quasi_stats_path %>

app/views/quasi_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Atk range:</strong>
  <%= @quasi_stat.atk_range %>
</p>

<p>
  <strong>Cast time:</strong>
  <%= @quasi_stat.cast_time %>
</p>

<p>
  <strong>Weight limit:</strong>
  <%= @quasi_stat.weight_limit %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @quasi_stat.energy %>
</p>

<%= link_to 'Edit', edit_quasi_stat_path(@quasi_stat) %> |
<%= link_to 'Back', quasi_stats_path %>